CREATE TABLE Book
(
    BOOK_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    AUTHOR VARCHAR(200) NOT NULL,
    USER_ID INTEGER
);
CREATE TABLE Book_usage
(
    BOOK_ID INTEGER NOT NULL,
    USED_SINCE DATETIME,
    USED_UNTIL DATETIME
);
CREATE TABLE Rating
(
    BOOK_ID INTEGER PRIMARY KEY NOT NULL,
    RATING INTEGER DEFAULT 0 NOT NULL
);
CREATE TABLE User
(
    USER_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(200) NOT NULL
);
